name: Health Check

on:
  schedule:
    # should run daily at midnight
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  url_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check the health of the URL
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://full-stack-open-part5-cicd.onrender.com/health
        max-attempts: 2
        retry-delay: 5s
